# Generated by Django 4.2.10 on 2024-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_answer_question_alter_question_test_set_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='questions',
            field=models.ManyToManyField(related_name='test_sets', to='tests.question'),
        ),
    ]
